var firstname="arpana",lastname="pandey",country="India",city="dhanbad",age=20,isMarried=false;
console.log(typeof(firstname),typeof(lastname),typeof(country),typeof(city),typeof(age),typeof(isMarried));
console.log('10'===10);
console.log(parseInt(9.8)===10);
Boolean('');
Boolean(false);
Boolean(0);
Boolean('Arpana');
Boolean(true);
Boolean(20);
console.log(4>3);
console.log(4>=3);
console.log(4<3);
console.log(4<=3);
console.log(4==4);
console.log(4===4);
console.log(4!=4);
console.log(4!==4);
console.log(4!='4');
console.log(4=='4');
console.log(4==='4');
var one="python";
var two="jargon";
console.log(one.length===two.length);
console.log(4>3&&10<12);
console.log(4>3&&10>12);
console.log(4>3||10<12);
console.log(4>3||10>12);
console.log(!(4>3));
console.log(!(4<3));
console.log(!(false));
console.log(!(4>3&&10<12));
console.log(!(4>3&&10>12));
const now=new Date();
console.log(now.getFullYear());
console.log(now.getMonth());
console.log(now.getDay());
console.log(now.getDate());
console.log(now.getHours());
console.log(now.getMinutes());
console.log(now.getTime());

